<template>
  <div class="home">
    <header>
      <nav>
        <router-link to="/">Inicio</router-link>
        <a href="#nosotros-ref">Nosotros</a>
        <a href="#categorias-div">Categorias</a>
        <router-link to="/login">Iniciar Sesión</router-link>
        <router-link to="/general">Posts</router-link>
        <router-link to="/create">Publicar</router-link>
      </nav>
      <section class="textos-header">
        <h1>Post-me</h1>
        <div class="frase shadow">
          <div class="f2">
            <h2>
              "Escribe algo que valga la pena leer o haz algo que valga la pena
              escribir".
            </h2>
            <h2>Benjamin Franklin</h2>
          </div>
        </div>
      </section>
      <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
      <div class="wave" style="height: 150px; overflow: hidden;">
        <svg
          viewBox="0 0 500 150"
          preserveAspectRatio="none"
          style="height: 100%; width: 100%;"
        >
          <path
            d="M-5.42,86.94 C279.00,142.20 383.97,-97.59 500.00,49.99 L500.00,150.00 L0.00,150.00 Z"
            style="stroke: none; fill: rgb(255, 255, 255);"
          />
        </svg>
      </div>
    </header>
    <main>
      <section class="sobre-nosotros" id="nosotros-ref">
        <h2>Sobre nosotros</h2>
        <div class="contenedor-sobre-nosotros">
          <img
            src="@/assets/Imagenes-home/nosotros.svg"
            alt
            class="imagen-nostros"
          />
          <div class="contenido-textos">
            <h3><span>1</span>Conocimiento infinito</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis
              possimus, sint expedita illum quod reiciendis obcaecati doloribus
              tempora! Totam aperiam voluptatum at delectus atque dolores
              cumque, ducimus adipisci ipsa placeat.
            </p>
            <h3 class="dos"><span>2</span>creatividad sin limites</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Id
              magnam, vel sed ad molestiae ipsum, iste voluptates doloremque
              recusandae, illo deleniti molestias est nisi dignissimos
              consequuntur assumenda! Ut, porro quisquam?
            </p>
          </div>
        </div>
      </section>
      <section class="portafolio" id="categorias-div">
        <div style="height: 150px; overflow: hidden;">
          <svg
            viewBox="0 0 500 150"
            preserveAspectRatio="none"
            style="height: 100%; width: 100%;"
          >
            <path
              d="M0.00,49.99 C128.89,193.51 249.66,-66.01 500.00,49.99 L500.00,0.00 L0.00,0.00 Z"
              style="stroke: none; fill: #ffffff;"
            />
          </svg>
        </div>
        <h2 class="titulob">Categorias</h2>
        <div class="contenedor-categorias">
          <div class="galeria-port">
            <div
              class="imagen-port"
              v-for="(item, index) of categories"
              v-bind:key="index"
            >
              <div class="fondo-img">
                <div class="imgbx">
                  <img src="@/assets/Imagenes-home/cat.svg" alt />
                </div>
                <div class="hover-galeria">
                  <h3>{{ item.name_category }}</h3>
                  <router-link to="/category">
                    <a @click="setIdCategory(index + 1)">Explorar</a>
                  </router-link>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div style="height: 150px; overflow: hidden;">
          <svg
            viewBox="0 0 500 150"
            preserveAspectRatio="none"
            style="height: 100%; width: 100%;"
          >
            <path
              d="M0.00,49.99 C150.00,150.00 349.20,-49.99 500.00,49.99 L500.00,150.00 L0.00,150.00 Z"
              style="stroke: none; fill: #ffffff;"
            />
          </svg>
        </div>
      </section>
      <section class="bloguers">
        <div class="contenedor-bloguers">
          <div class="cards">
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>Preguntas frecuentes</h2>
                <a href="#">Click Aquí</a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>Contacto</h2>
                <a href="#">
                  <i class="fab fa-facebook"></i>
                </a>
                <a href="#">
                  <i class="fab fa-telegram"></i>
                </a>
                <a href="#">
                  <i class="fas fa-at"></i>
                </a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>Manual</h2>
                <a href="#">Click Aquí</a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>TIPS</h2>
                <a href="#">Ver más</a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer class="marca">
        <h2>&copy; NT Design | Post-Me</h2>
      </footer>
    </main>
  </div>
</template>

<script>
import { mapState, mapMutations } from "vuex";
export default {
  name: "PostMeHome",
  data() {
    return {
      categories: [],
    };
  },
  methods: {
    async getCategories() {
      const datos = await fetch(
        `https://software-app-blog.herokuapp.com/categories`
      ).then((res) => res.json());
      this.categories = datos["categories"];
      this.setCategories(this.categories);
    },
    ...mapMutations(["setIdCategory", "setCategories"]),
  },
  created() {
    this.getCategories();
  },
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap");
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: "Poppins", sans-serif;
}
:root {
  --colores-h: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #bcff00,
    #46f8f3
  );
  --colores3: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  --colores2: -webkit-linear-gradient(5deg, #00fff5, #ff59c1, #e762ff);
  --color-cat1: #bcff00;
  --color-cat2: #fc8fba;
  --color-cat3: #ffc100;
  --color-cat4: #00feca;
  --color-cat5: #f84f0c;
  --color-cat6: #0000fe;
  --color-cat7: #fe1188;
  --color-cat8: #f8ecc5;
  --color-cat9: #be7b4a;
}
/*---------------HEADER---------------*/
header {
  width: 100%;
  height: 750px;
  background: #7f00ff; /* fallback for old browsers*/
  background: -webkit-linear-gradient(
      180deg,
      hsla(0, 0%, 0%, 0.5),
      hsla(0, 0%, 0%, 0.3),
      hsla(0, 0%, 0%, 0.5)
    ),
    url(../assets/Imagenes-home/fondon2.jpg); /* Chrome 10-25, Safari 5.1-6*/
  background: linear-gradient(
      180deg,
      hsla(0, 0%, 0%, 0.5),
      hsla(0, 0%, 0%, 0.3),
      hsla(0, 0%, 0%, 0.5)
    ),
    url(../assets/Imagenes-home/fondon4.jpg); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  background-size: cover;
  background-attachment: fixed;
  position: relative;
  text-align: center;
}
nav {
  text-align: right;
  padding: 30px 50px 0 0;
}
nav > a {
  font-family: "Pacifico", cursive;
  font-size: 22px;
  text-decoration: none;
  margin-right: 12px;
}
nav > a:hover {
  text-decoration: underline;
}
nav a:nth-child(1) {
  color: #00feca;
}
nav a:nth-child(2) {
  color: #bcff00;
}
nav a:nth-child(3) {
  color: #ffc100;
}
nav a:nth-child(4) {
  color: #ffee00;
}
nav a:nth-child(5) {
  color: #ff59c1;
}
nav a:nth-child(6) {
  color: white;
}
.wave {
  position: absolute;
  bottom: 0;
  width: 100%;
}
header .textos-header {
  display: flex;
  height: 430px;
  width: 100%;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
.textos-header h1 {
  background: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  font-size: 135px;
  font-family: "Rock Salt", cursive;
}
.textos-header .frase {
  position: relative;
  margin: 2px;
  min-width: 320px;
  min-height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 2px;
  border-radius: 15px;
  background: linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  flex-direction: column;
  justify-content: center;
}
.frase .f2 {
  position: relative;
  margin: 1px;
  min-width: 310px;
  min-height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 5px;
  border-radius: 10px;
  background: rgb(14, 13, 13);
  color: white;
  flex-direction: column;
  justify-content: center;
}
.frase h2:nth-child(1) {
  font-weight: 250;
  letter-spacing: 2px;
  font-size: 27px;
}
.frase h2:nth-child(2) {
  background: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  font-weight: 400;
  font-size: 25px;
  letter-spacing: 1px;
  /*   font-family: "Roboto Mono", monospace; */
}

/*---------------NOSOTROS---------------*/
.sobre-nosotros {
  padding: 20 px 0;
  width: 95%;
  max-width: 1200px;
  margin: auto;
  overflow: hidden;
}
.sobre-nosotros h2 {
  color: #894bf8;
  font-size: 30px;
  font-family: "Rock Salt", cursive;
  text-align: center;
}
.contenedor-sobre-nosotros {
  display: flex;
  justify-content: space-evenly;
  /*margin-bottom: 85px;*/
  margin-top: 0;
  margin-left: 0;
  margin-right: 0;
  margin-bottom: 60px;
  padding: 0;
}
.imagen-nostros {
  width: 35%;
  margin-right: 75px;
}
.contenedor-sobre-nostros .contenido-textos {
  width: 48%;
  margin-left: 80px;
}
.contenido-textos h3 {
  margin-top: 75px;
  margin-bottom: 15px;
  color: #7f00ff;
}
.contenido-textos .dos {
  margin-top: 30px;
  margin-bottom: 15px;
  color: #7f00ff;
}
.contenido-textos h3 span {
  background: #7f00ff;
  color: floralwhite;
  border-radius: 50%;
  display: inline-block;
  text-align: center;
  width: 30px;
  height: 30px;
  padding: 2px;
  box-shadow: 0 0 6px rgba(0, 0, 0, 0.5);
  margin-right: 5px;
}
.contenido-textos p {
  padding: 0px 0px 30px 15px;
  /*   font-family: "Roboto Mono", monospace; */
  font-weight: 150;
  text-align: justify;
}

/*---------------Galeria-Categorías---------------*/
.portafolio {
  background: #7f00ff; /* fallback for old browsers*/
  background: -webkit-linear-gradient(
      180deg,
      hsla(0, 0%, 0%, 0.6),
      hsla(0, 0%, 0%, 0.3),
      hsla(0, 0%, 0%, 0.6)
    ),
    url(../assets/Imagenes-home/fondocat3.jpg); /* Chrome 10-25, Safari 5.1-6*/
  background: linear-gradient(
      180deg,
      hsla(0, 0%, 0%, 0.6),
      hsla(0, 0%, 0%, 0.3),
      hsla(0, 0%, 0%, 0.6)
    ),
    url(../assets/Imagenes-home/fondocat3.jpg); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  background-size: cover;
  background-attachment: fixed;
}
.contenedor-categorias {
  margin-bottom: 100px;
  padding: 0;
}
.titulob {
  background: linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  /* color: #ffffff; */
  font-size: 45px;
  font-family: "Rock Salt", cursive;
  text-align: center;
  margin: 0px;
  padding: 0px;
}
.contenedor-categorias .galeria-port {
  margin-top: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  min-height: 10vh;
}

.galeria-port .imagen-port .fondo-img {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  border-radius: 45px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.galeria-port .imagen-port {
  position: relative;
  width: 250px;
  height: 200px;
  background: #ffffff;
  display: block;
  margin: 15px 32px;
  border-radius: 45px;
  z-index: 2;
}
.galeria-port .imagen-port .fondo-img .hover-galeria {
  position: relative;
  width: 98%;
  height: 98%;
  background: white;
  border-radius: 45px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.galeria-port .imagen-port .fondo-img .imgbx {
  position: absolute;
  width: 98%;
  height: 98%;
  background: black;
  border-radius: 45px;
  z-index: 2;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  transition: 0.5s ease-in-out;
}

.galeria-port .imagen-port:hover .fondo-img .imgbx {
  width: 120px;
  height: 120px;
  left: -60px;
  top: calc(50% - 50px);
  transition: 0.5s ease-in-out;
  background: black;
}
.galeria-port .imagen-port .fondo-img .imgbx:before {
  content: attr(data-text);
  position: absolute;
  text-align: center;
  font-size: 2em;
  color: rgba(137, 75, 248);
  font-weight: 500;
  bottom: 10px;
  left: 0;
  width: 100%;
}
.galeria-port .imagen-port .fondo-img .imgbx img {
  max-width: 185px;
  transition: 0.5 ease-in-out;
}
.galeria-port .imagen-port:hover .fondo-img .imgbx img {
  max-width: 75px;
}
.galeria-port .imagen-port .hover-galeria {
  position: absolute;
  height: 100%;
  padding-left: 30px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.galeria-port .imagen-port .fondo-img .hover-galeria h3 {
  margin-bottom: 5px;
  font-size: 22px;
  color: #7f00ff;
}
.galeria-port .imagen-port .fondo-img .hover-galeria p {
  margin-bottom: 5px;
  font-size: 13px;
  text-align: justify;
}
.galeria-port .imagen-port .fondo-img .hover-galeria a {
  display: inline-block;
  margin-top: 0px;
  padding: 5px 10px;
  border-radius: 8px;
  font-size: 16px;
  background: #7f00ff;
  text-decoration: none;
  color: #ffffff;
}

/*---------------BLOGUERS---------------*/
.contenedor-bloguers {
  margin-top: 0;
  margin-left: 0;
  margin-right: 0;
  padding: 0;
  margin-bottom: 50px;
}
.contenedor-bloguers .cards {
  margin-top: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  min-height: 10vh;
}
.card {
  position: relative;
  width: 300px;
  height: 300px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 40px;
  background: #ffffff;
  transition: 0.5s;
}
.card:hover {
  height: 400px;
}
.card .imgBox {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  padding: 10px;
  border-radius: 45px;
  box-sizing: border-box;
}
.card .imgBox img {
  max-width: 100%;
  opacity: 0.35;
  transition: 0.5s;
}
.card:hover .imgBox img {
  opacity: 1;
}
.card:before {
  content: "";
  position: absolute;
  top: -2px;
  left: -2px;
  right: -2px;
  bottom: -2px;
  background: #7f00ff;
  z-index: -1;
}
.card:after {
  content: "";
  position: absolute;
  top: -2px;
  left: -2px;
  right: -2px;
  bottom: -2px;
  background: #7f00ff;
  z-index: -2;
  filter: blur(40px);
}
.card:before,
.card:after {
  background: linear-gradient(235deg, #894bf8, #00feca, #ef4cff);
}
.card:nth-child(2):before,
.card:nth-child(2):after {
  background: linear-gradient(235deg, #00feca, #46c9da, #948ce7);
}
.card:nth-child(2):before,
.card:nth-child(2):after {
  background: linear-gradient(
    235deg,
    rgb(250, 246, 23),
    rgb(248, 12, 59),
    #1f00fe
  );
}
.card .contenido-texto-card {
  position: absolute;
  bottom: 0;
  left: 10px;
  right: 10px;
  bottom: 10px;
  height: 90px;
  background: rgba(250, 247, 247, 0.3);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  opacity: 0;
  transition: 0.5s;
}
.card:hover .contenido-texto-card {
  opacity: 1;
}
.card .contenido-texto-card h4 {
  font-size: 20px;
  color: #7f00ff;
  font-family: "Pacifico", cursive;
  line-height: 20px;
  letter-spacing: 1px;
}
.card .contenido-texto-card p {
  font-size: 8px;
  color: #f1e9e9;
  font-family: "Roboto Mono", monospace;
  font-weight: 150;
  text-align: center;
  letter-spacing: 2px;
}

/*---------------CÍRCULOS---------------*/
.square {
  position: relative;
  width: 230px;
  height: 200px;
  margin: 10px 60px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.square span:nth-child(1) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid cyan;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate 6s linear infinite;
  background: linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  filter: blur(18px);
  /* background: rgba(0, 255, 255, 0.5); */
}
/*.square:hover span:nth-child(1){
    border: none;
    background: rgba(0,255, 255, .5);
}*/
.square span:nth-child(2) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid fuchsia;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate2 4s linear infinite;
  background: rgba(255, 0, 255, 0.5);
}
/*.square:hover span:nth-child(2){
    border: none;
    background: rgba(255,0, 255, .5);
}*/
.square span:nth-child(3) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid #7f00ff;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate 10s linear infinite;
  background: rgba(127, 0, 255, 0.5);
}
/*.square:hover span:nth-child(3){
    border: none;
    background: rgba(127,0, 255, .5);
}*/
@keyframes animate {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
@keyframes animate2 {
  0% {
    transform: rotate(360deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
.contents {
  position: relative;
  padding: 40px 60px;
  text-align: center;
  transition: 0.5s;
  z-index: 1000;
}
.contents h2 {
  color: white;
  font-size: 22px;
  /* text-transform: lowercase; */
  font-weight: 400;
}
.contents a {
  display: inline-block;
  margin-top: 10px;
  padding: 5px 10px;
  font-weight: 600;
  border-radius: 8px;
  font-size: 13px;
  background: rgb(247, 247, 247);
  text-decoration: none;
  color: #894bf8;
  /* background: -webkit-linear-gradient(
    175deg,
    #00fff5,
    #bcff00,
    #ffee00,
    #ffc100,
    #ff59c1,
    #e762ff
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent; */
}
/*FINAL*/
.marca {
  /*background: linear-gradient(to right, hsla(300, 100%, 50%, 0.28), hsla(270, 100%, 50%, 0.95));*/
  margin: 0;
  padding: 0;
  align-items: center;
}
.marca h2 {
  text-align: center;
  color: #7f00ff;
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
  font-size: 20px;
}
</style>
