<template>
  <div class="home">
    <header>
      <nav>
        <router-link to="/">Inicio</router-link>
        <router-link to="/about">Nosotros</router-link>
        <router-link to="/login">Iniciar Sesión</router-link>
        <!-- <a href="#">Inicio</a>
        <a href="#">Nosotros</a>
        <a href="#">Menu</a>
        <a href="#">Iniciar sesion</a>
        <a href="#">Registrate</a>-->
      </nav>
      <section class="textos-header">
        <h1>Post-me</h1>
        <h2>
          "Escribe algo que valga la pena leer o haz algo que valga la pena
          escribir".
        </h2>
        <h2>Benjamin Franklin</h2>
      </section>
      <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
      <div class="wave" style="height: 150px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
          <path
            d="M-5.42,86.94 C279.00,142.20 383.97,-97.59 500.00,49.99 L500.00,150.00 L0.00,150.00 Z"
            style="stroke: none; fill: rgb(255, 255, 255);"
          />
        </svg>
      </div>
    </header>
    <main>
      <section class="sobre-nosotros">
        <h2>Sobre nosotros</h2>
        <div class="contenedor-sobre-nosotros">
          <img src="@/assets/Imagenes-home/nosotros.svg" alt class="imagen-nostros" />
          <div class="contenido-textos">
            <h3>
              <span>1</span>Conocimiento infinito
            </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis
              possimus, sint expedita illum quod reiciendis obcaecati doloribus
              tempora! Totam aperiam voluptatum at delectus atque dolores
              cumque, ducimus adipisci ipsa placeat.
            </p>
            <h3 class="dos">
              <span>2</span>creatividad sin limites
            </h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Id
              magnam, vel sed ad molestiae ipsum, iste voluptates doloremque
              recusandae, illo deleniti molestias est nisi dignissimos
              consequuntur assumenda! Ut, porro quisquam?
            </p>
          </div>
        </div>
      </section>
      <section class="portafolio">
        <div style="height: 150px; overflow: hidden;">
          <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
            <path
              d="M0.00,49.99 C128.89,193.51 249.66,-66.01 500.00,49.99 L500.00,0.00 L0.00,0.00 Z"
              style="stroke: none; fill: #ffffff;"
            />
          </svg>
        </div>
        <h2 class="titulob">Categorias</h2>
        <div class="contenedor-categorias">
          <div class="galeria-port">
            <div class="imagen-port">
              <div class="imgbx" data-text="Jardinería">
                <img src="@/assets/Imagenes-home/plantas.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Jardinería</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de temas relacionados a las planatas y
                  mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Belleza">
                <img src="@/assets/Imagenes-home/belleza.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Belleza</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de temas relacionados a las belleza,
                  cosmeticos y mucho más
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Comida">
                <img src="@/assets/Imagenes-home/comida.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Comida</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de temas relacionados a las comida,
                  recetas, health life style etc y mucho mas
                </p>
                <router-link to="/food">Ver más</router-link>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Ejercicio">
                <img src="@/assets/Imagenes-home/ejercicio.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Ejercicio</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de temas relacionados con el ejercicio,
                  meditación y mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Espectáculos">
                <img src="@/assets/Imagenes-home/espectaculo.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Espectáculos</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de temas relacionados a los espectáculos y
                  mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Tecnología">
                <img src="@/assets/Imagenes-home/tecnologia.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Tecnología</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas hacerca de temas relacionados a las tecnología,
                  programación, informática y mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Manualidades">
                <img src="@/assets/Imagenes-home/manualidades.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Manualides</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a crear
                  haciendo uso de tu imaginación, manualidades, Diy y mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Libros">
                <img src="@/assets/Imagenes-home/libro.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Libros</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de poesia, libros y mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
            <div class="imagen-port">
              <div class="imgbx" data-text="Mascotas">
                <img src="@/assets/Imagenes-home/mascotas.svg" alt />
              </div>
              <div class="hover-galeria">
                <h3>Libros</h3>
                <p>
                  En esta categoría podras encontrar blogs que te ayuden a
                  conocer mas acerca de los animales y mucho mas
                </p>
                <a href="#">Ver más</a>
              </div>
            </div>
          </div>
        </div>
        <div style="height: 150px; overflow: hidden;">
          <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
            <path
              d="M0.00,49.99 C150.00,150.00 349.20,-49.99 500.00,49.99 L500.00,150.00 L0.00,150.00 Z"
              style="stroke: none; fill: #ffffff;"
            />
          </svg>
        </div>
      </section>
      <section class="bloguers">
        <div class="contenedor-bloguers">
          <div class="cards">
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>PREGUNTAS FRECUENTES</h2>
                <a href="#">Click Aquí</a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>CONTACTO</h2>
                <a href="#">
                  <i class="fab fa-facebook"></i>
                </a>
                <a href="#">
                  <i class="fab fa-telegram"></i>
                </a>
                <a href="#">
                  <i class="fas fa-at"></i>
                </a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>MANUAL</h2>
                <a href="#">Click Aquí</a>
              </div>
            </div>
            <div class="square">
              <span></span>
              <span></span>
              <span></span>
              <div class="contents">
                <h2>TIPS</h2>
                <a href="#">Ver más</a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer class="marca">
        <h2>&copy; NT Design | Post-Me</h2>
      </footer>
    </main>
  </div>
</template>

<script>
export default {
  name: "PostMeHome"
};
</script>

<style scoped>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
/*---------------HEADER---------------*/
header {
  width: 100%;
  height: 685px;
  background: #7f00ff; /* fallback for old browsers*/
  background: -webkit-linear-gradient(
      to right,
      hsla(300, 100%, 50%, 0.38),
      hsla(270, 100%, 50%, 0.95)
    ),
    url(../assets/Imagenes-home/fondo2.jpg); /* Chrome 10-25, Safari 5.1-6*/
  background: linear-gradient(
      to right,
      hsla(300, 100%, 50%, 0.28),
      hsla(270, 100%, 50%, 0.95)
    ),
    url(../assets/Imagenes-home/fondo2.jpg); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  background-size: cover;
  background-attachment: fixed;
  position: relative;
  text-align: center;
}
nav {
  text-align: right;
  padding: 30px 50px 0 0;
}
nav > a {
  color: floralwhite;
  /*font-weight: 300;*/
  font-family: "Pacifico", cursive;
  font-size: 18px;
  text-decoration: none;
  margin-right: 12px;
}
nav > a:hover {
  text-decoration: underline;
}
.wave {
  position: absolute;
  bottom: 0;
  width: 100%;
}
header .textos-header {
  display: flex;
  height: 430px;
  width: 100%;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}
.textos-header h1 {
  color: floralwhite;
  font-size: 85px;
  font-family: "Rock Salt", cursive;
}
.textos-header h2 {
  color: floralwhite;
  font-weight: 200;
  font-size: 25px;
  font-family: "Roboto Mono", monospace;
}

/*---------------NOSOTROS---------------*/
.sobre-nosotros {
  padding: 20 px 0;
  width: 95%;
  max-width: 1200px;
  margin: auto;
  overflow: hidden;
}
.sobre-nosotros h2 {
  color: #894bf8;
  font-size: 30px;
  font-family: "Rock Salt", cursive;
  text-align: center;
}
.contenedor-sobre-nosotros {
  display: flex;
  justify-content: space-evenly;
  /*margin-bottom: 85px;*/
  margin-top: 0;
  margin-left: 0;
  margin-right: 0;
  margin-bottom: 60px;
  padding: 0;
}
.imagen-nostros {
  width: 45%;
  margin-right: 75px;
}
.contenedor-sobre-nostros .contenido-textos {
  width: 48%;
  margin-left: 80px;
}
.contenido-textos h3 {
  margin-top: 75px;
  margin-bottom: 15px;
  color: #7f00ff;
}
.contenido-textos .dos {
  margin-top: 30px;
  margin-bottom: 15px;
  color: #7f00ff;
}
.contenido-textos h3 span {
  background: #7f00ff;
  color: floralwhite;
  border-radius: 50%;
  display: inline-block;
  text-align: center;
  width: 30px;
  height: 30px;
  padding: 2px;
  box-shadow: 0 0 6px rgba(0, 0, 0, 0.5);
  margin-right: 5px;
}
.contenido-textos p {
  padding: 0px 0px 30px 15px;
  font-family: "Roboto Mono", monospace;
  font-weight: 150;
  text-align: justify;
}

/*---------------Galeria-Categorías---------------*/
.portafolio {
  background: #7f00ff; /* fallback for old browsers */
  background: -webkit-linear-gradient(
      to right,
      hsla(300, 100%, 50%, 0.38),
      hsla(270, 100%, 50%, 0.95)
    ),
    url(../assets/Imagenes-home/fondo5.jpg); /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(
      to right,
      hsla(300, 100%, 50%, 0.28),
      hsla(270, 100%, 50%, 0.95)
    ),
    url(../assets/Imagenes-home/fondo5.jpg); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  background-size: cover;
  background-attachment: fixed;
}
.contenedor-categorias {
  margin: 0;
  padding: 0;
}
.titulob {
  color: #ffffff;
  font-size: 45px;
  font-family: "Rock Salt", cursive;
  text-align: center;
  margin: 0px;
  padding: 0px;
}
.contenedor-categorias .galeria-port {
  margin-top: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  min-height: 10vh;
}
.galeria-port .imagen-port {
  position: relative;
  width: 280px;
  height: 210px;
  background: #ffffff;
  display: block;
  margin: 15px 32px;
  border-radius: 45px;
}
.galeria-port .imagen-port .imgbx {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #ffffff;
  border-radius: 45px;
  z-index: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
  transition: 0.5s ease-in-out;
}
.galeria-port .imagen-port:hover .imgbx {
  width: 125px;
  height: 125px;
  left: -60px;
  top: calc(50% - 60px);
  transition: 0.5s ease-in-out;
  background: #894bf8;
}
.galeria-port .imagen-port .imgbx:before {
  content: attr(data-text);
  position: absolute;
  text-align: center;
  font-size: 2em;
  color: rgba(137, 75, 248);
  font-weight: 500;
  bottom: 10px;
  left: 0;
  width: 100%;
}
.galeria-port .imagen-port .imgbx img {
  max-width: 185px;
  transition: 0.5 ease-in-out;
}
.galeria-port .imagen-port:hover .imgbx img {
  max-width: 75px;
}
.galeria-port .imagen-port .hover-galeria {
  position: absolute;
  right: 0;
  width: calc(100% - 60px);
  height: 100%;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.galeria-port .imagen-port .hover-galeria h3 {
  margin-bottom: 5px;
  font-size: 22px;
  color: #7f00ff;
}
.galeria-port .imagen-port .hover-galeria p {
  margin-bottom: 5px;
  font-size: 16px;
  text-align: justify;
}
.galeria-port .imagen-port .hover-galeria a {
  display: inline-block;
  margin-top: 10px;
  padding: 5px 10px;
  border-radius: 8px;
  font-size: 16px;
  background: #7f00ff;
  text-decoration: none;
  color: #ffffff;
}

/*---------------BLOGUERS---------------*/
.contenedor-bloguers {
  margin-top: 0;
  margin-left: 0;
  margin-right: 0;
  padding: 0;
  margin-bottom: 50px;
}
.contenedor-bloguers .cards {
  margin-top: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  min-height: 10vh;
}
.card {
  position: relative;
  width: 300px;
  height: 300px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 40px;
  background: #ffffff;
  transition: 0.5s;
}
.card:hover {
  height: 400px;
}
.card .imgBox {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  padding: 10px;
  border-radius: 45px;
  box-sizing: border-box;
}
.card .imgBox img {
  max-width: 100%;
  opacity: 0.35;
  transition: 0.5s;
}
.card:hover .imgBox img {
  opacity: 1;
}
.card:before {
  content: "";
  position: absolute;
  top: -2px;
  left: -2px;
  right: -2px;
  bottom: -2px;
  background: #7f00ff;
  z-index: -1;
}
.card:after {
  content: "";
  position: absolute;
  top: -2px;
  left: -2px;
  right: -2px;
  bottom: -2px;
  background: #7f00ff;
  z-index: -2;
  filter: blur(40px);
}
.card:before,
.card:after {
  background: linear-gradient(235deg, #894bf8, #00feca, #ef4cff);
}
.card:nth-child(2):before,
.card:nth-child(2):after {
  background: linear-gradient(235deg, #00feca, #46c9da, #948ce7);
}
.card:nth-child(2):before,
.card:nth-child(2):after {
  background: linear-gradient(
    235deg,
    rgb(250, 246, 23),
    rgb(248, 12, 59),
    #1f00fe
  );
}
.card .contenido-texto-card {
  position: absolute;
  bottom: 0;
  left: 10px;
  right: 10px;
  bottom: 10px;
  height: 90px;
  background: rgba(250, 247, 247, 0.3);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  opacity: 0;
  transition: 0.5s;
}
.card:hover .contenido-texto-card {
  opacity: 1;
}
.card .contenido-texto-card h4 {
  font-size: 20px;
  color: #7f00ff;
  font-family: "Pacifico", cursive;
  line-height: 20px;
  letter-spacing: 1px;
}
.card .contenido-texto-card p {
  font-size: 8px;
  color: #f1e9e9;
  font-family: "Roboto Mono", monospace;
  font-weight: 150;
  text-align: center;
  letter-spacing: 2px;
}

/*---------------CÍRCULOS---------------*/
.square {
  position: relative;
  width: 225px;
  height: 225px;
  margin: 35px;
  display: flex;
  justify-content: center;
  align-items: center;
}
.square span:nth-child(1) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid cyan;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate 6s linear infinite;
  background: rgba(0, 255, 255, 0.5);
}
/*.square:hover span:nth-child(1){
    border: none;
    background: rgba(0,255, 255, .5);
}*/
.square span:nth-child(2) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid fuchsia;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate2 4s linear infinite;
  background: rgba(255, 0, 255, 0.5);
}
/*.square:hover span:nth-child(2){
    border: none;
    background: rgba(255,0, 255, .5);
}*/
.square span:nth-child(3) {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 2px solid #7f00ff;
  border-radius: 38% 62% 63% 37% / 41% 44% 56% 59%;
  transition: 0.5s;
  animation: animate 10s linear infinite;
  background: rgba(127, 0, 255, 0.5);
}
/*.square:hover span:nth-child(3){
    border: none;
    background: rgba(127,0, 255, .5);
}*/
@keyframes animate {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
@keyframes animate2 {
  0% {
    transform: rotate(360deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
.contents {
  position: relative;
  padding: 40px 60px;
  color: white;
  text-align: center;
  transition: 0.5s;
  z-index: 1000;
}
.contents a {
  display: inline-block;
  margin-top: 10px;
  padding: 5px 10px;
  border-radius: 8px;
  font-size: 16px;
  background: rgb(247, 247, 247);
  text-decoration: none;
  color: #7f00ff;
}
/*FINAL*/
.marca {
  /*background: linear-gradient(to right, hsla(300, 100%, 50%, 0.28), hsla(270, 100%, 50%, 0.95));*/
  margin: 0;
  padding: 0;
  align-items: center;
}
.marca h2 {
  text-align: center;
  color: #7f00ff;
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
  font-size: 20px;
}
</style>